# Tomcat Port:
server:
  port: 8888

# Config Repo:
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///${HOME}/microservices_config_repo

# Show sensitive information for endpoints:
endpoints:
  sensitive: true

# Security for endpoints:
management:
  security:
    enabled: false

# Enable BASIC Authentication:
security:
  basic:
    enabled: true
  user:
    name: user1
    password: changeme

