#------------------------------------------------------------------------------#
# Application YAML #
# inside ./src/main/resources/application.yml
#------------------------------------------------------------------------------#
debug: true

# Disable security for Actuator endpoints:
# otherwise, you will see a 401 UnAuthorized Error
management.security.enabled: true

# Enable BASIC Authentication for Service Endpoints
security.basic.enabled: true

security:
  user:
    name: user2
    password: changeme



##---------------------------------------------------------------------------##
